"""First migration

Revision ID: 29cee62cb562
Revises: 
Create Date: 2020-08-31 20:48:17.288247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cee62cb562'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establishment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('dono', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(), nullable=True),
    sa.Column('cliente', sa.String(), nullable=True),
    sa.Column('estabelecimento', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento'], ['establishment.cnpj'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('establishment')
    # ### end Alembic commands ###
